from .Cargo import *
from .ContatoFuncionario import *
from .DocumentoFuncionario import *
from .EnderecoFuncionario import *
from .Funcionario import *
from .health_model import *
from .HonorariosAfastamento import *
from .HonorariosCalculoAuditoria import *
from .HonorariosTipoAfastamento import *
from .Setor import *
from .Upload import *
from .LogsBcadastro import *
from .ComprovantesDePagamento import *
from .DjoRetFile import *
from .DjoRetFileTipoA import *
from .DjoRetFileTipoB import *
from .DjoRetFileTipoC import *
from .DjoRetFileCabecalho import *
from .AuthSession import *
from .Page_model import *
from .AuthPerfil import *
from .AuthRegra import *
from .AuthAplicacao import *
from .SolicitacaoAcesso import *
from .FolhaHonorarios import *
from .HonorarioPagamento import *
from .Chamado import *
from .Notificacao import *
from .ReportModel import *
from .ReportMessage import *
from .Cursos import *
from .CursosOfertas import *
from .CertificadosTemplate import *
from .PresencasCursos import *
from .InscricoesCursos import *
from .ListaEsperaCursos import *
from .LogModel import *
from .BucketFile import *
from .BucketGroup import *
from .Aula import *
from .HonorarioAgrupamentoFuncionarios import *
from .Ata import *
from .AcervoIndexador import *
from .AppSettings import *
from .Cron import *
from .Fila import *
from .ChaveAPI import *
from .ConfiguracaoSistema import *
from .ChaveAPIAplicacoes import *
from .MidiaIndoorSlide import *
from .AssistenteIaLog import *
from .AssistenteIaConversa import *
from .AssistenteIaMensagem import *
from .AssistenteIaContextoDocumento import *
from .AssistenteIaConfig import *
