"""add notificacao

Revision ID: 0dbd553fe36d
Revises: b627c1da6861
Create Date: 2025-11-24 14:01:08.737873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0dbd553fe36d'
down_revision: Union[str, None] = 'b627c1da6861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_funcionario_id'), 'notificacoes', ['funcionario_id'], unique=False)
    op.create_index(op.f('ix_notificacoes_tipo'), 'notificacoes', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificacoes_titulo'), 'notificacoes', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificacoes_titulo'), table_name='notificacoes')
    op.drop_index(op.f('ix_notificacoes_tipo'), table_name='notificacoes')
    op.drop_index(op.f('ix_notificacoes_funcionario_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
