"""corrigindo questao das chaves estrangeiras e limpando tabelas que nao vao ser utilizadas

Revision ID: 2063073efd35
Revises: 32d017ec7f31
Create Date: 2025-10-22 11:01:25.502213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2063073efd35'
down_revision: Union[str, None] = '32d017ec7f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aplicacao_nome'), 'aplicacao', ['nome'], unique=True)
    op.create_index(op.f('ix_aplicacao_slug'), 'aplicacao', ['slug'], unique=True)

    op.drop_table('role_permissions')

    op.drop_table('user_roles')

    op.drop_table('role_ad_groups')

    op.drop_index(op.f('ix_ad_groups_nome'), table_name='ad_groups')
    op.drop_table('ad_groups')

    op.drop_index(op.f('ix_roles_nome'), table_name='roles')
    op.drop_table('roles')

    op.drop_index(op.f('ix_permissions_nome'), table_name='permissions')
    op.drop_table('permissions')

    op.drop_index(op.f('ix_applicacao_nome'), table_name='applicacao')
    op.drop_index(op.f('ix_applicacao_slug'), table_name='applicacao')
    op.drop_table('applicacao')

    op.drop_index(op.f('ix_users_matricula'), table_name='users')
    op.drop_table('users')

    op.add_column('perfil', sa.Column('aplicacao_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'perfil', 'aplicacao', ['aplicacao_id'], ['id'])
    op.add_column('regra', sa.Column('perfil_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'regra', 'perfil', ['perfil_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regra', type_='foreignkey')
    op.drop_column('regra', 'perfil_id')
    op.drop_constraint(None, 'perfil', type_='foreignkey')
    op.drop_column('perfil', 'aplicacao_id')
    op.create_table('role_ad_groups',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ad_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], name=op.f('role_ad_groups_ad_group_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_ad_groups_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'ad_group_id', name=op.f('role_ad_groups_pkey'))
    )
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_roles_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_roles_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('matricula', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ultimo_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_matricula'), 'users', ['matricula'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_permissions_permission_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_permissions_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('applicacao',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('applicacao_pkey'))
    )
    op.create_index(op.f('ix_applicacao_slug'), 'applicacao', ['slug'], unique=True)
    op.create_index(op.f('ix_applicacao_nome'), 'applicacao', ['nome'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('permissions_pkey'))
    )
    op.create_index(op.f('ix_permissions_nome'), 'permissions', ['nome'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_index(op.f('ix_roles_nome'), 'roles', ['nome'], unique=True)
    op.create_table('ad_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ad_groups_pkey'))
    )
    op.create_index(op.f('ix_ad_groups_nome'), 'ad_groups', ['nome'], unique=True)
    op.drop_index(op.f('ix_aplicacao_slug'), table_name='aplicacao')
    op.drop_index(op.f('ix_aplicacao_nome'), table_name='aplicacao')
    op.drop_table('aplicacao')
    # ### end Alembic commands ###
