"""criando novas tabelas

Revision ID: ff3a60146918
Revises: b0281fba1573
Create Date: 2025-11-12 11:29:57.400698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff3a60146918'
down_revision: Union[str, None] = 'b0281fba1573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folhas_honorarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('mes', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('montante', sa.Float(), nullable=False),
    sa.Column('liberar_rh', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honorarios_pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('unidade_honoraria', sa.Float(), nullable=False),
    sa.Column('valor_recebido', sa.Float(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('folha_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folha_id'], ['folhas_honorarios.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honorarios_pagamentos_folha_id'), 'honorarios_pagamentos', ['folha_id'], unique=False)
    op.create_index(op.f('ix_honorarios_pagamentos_funcionario_id'), 'honorarios_pagamentos', ['funcionario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_honorarios_pagamentos_funcionario_id'), table_name='honorarios_pagamentos')
    op.drop_index(op.f('ix_honorarios_pagamentos_folha_id'), table_name='honorarios_pagamentos')
    op.drop_table('honorarios_pagamentos')
    op.drop_table('folhas_honorarios')
    # ### end Alembic commands ###
