"""criando parte de aprovacoes novamente

Revision ID: 0635e3c152f7
Revises: ed26b439583c
Create Date: 2025-11-03 15:51:47.091417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0635e3c152f7'
down_revision: Union[str, None] = 'ed26b439583c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('solicitante', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sistema', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('justificativa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataCriacao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aprovacoes_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('solicitacaoId', sa.Integer(), nullable=False),
    sa.Column('aprovador', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('justificativa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dataAprovacao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['solicitacaoId'], ['solicitacoes_acesso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aprovacoes_acesso')
    op.drop_table('solicitacoes_acesso')
    # ### end Alembic commands ###
