"""change unique values regra

Revision ID: 2ef86c356a95
Revises: 3aa98618001d
Create Date: 2025-10-24 12:40:35.709615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ef86c356a95'
down_revision: Union[str, None] = '3aa98618001d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_regra_codigo_setor_codigo_cargo_matricula_perfil_id'), 'regra', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_regra_codigo_setor_codigo_cargo_matricula_perfil_id'), 'regra', ['codigo_setor', 'codigo_cargo', 'matricula', 'perfil_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
