"""initial

Revision ID: b3b09305fa4e
Revises: 
Create Date: 2025-10-07 15:16:09.267366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3b09305fa4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('escolaridade_cargo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_cargos_nome')
    )
    op.create_table('health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honorarios_calc_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('escopo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('conteudo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regra_aplicada', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honorarios_calc_audit_escopo'), 'honorarios_calc_audit', ['escopo'], unique=False)
    op.create_table('honorarios_calc_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('codigo_regra', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('escopo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=True),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.Column('condicao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honorarios_calc_rules_codigo_regra'), 'honorarios_calc_rules', ['codigo_regra'], unique=False)
    op.create_index(op.f('ix_honorarios_calc_rules_escopo'), 'honorarios_calc_rules', ['escopo'], unique=False)
    op.create_table('honorarios_tipos_afastamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('excecao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_tipo_afastamento_codigo'),
    sa.UniqueConstraint('tipo', name='uq_tipo_afastamento_tipo')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('app', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_app'), 'permissions', ['app'], unique=True)
    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=False),
    sa.Column('sigla', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'sigla', name='uq_setores_nome_sigla')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nome_arquivo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('extensao', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nome_social', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('nome_mae', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('nome_pai', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('naturalidade', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('uf_nasc', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(length=55), nullable=True),
    sa.Column('estado_civil', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('escolaridade', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('regime', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.Column('raca_cor', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('tipo_deficiencia', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('grupo_sanguineo', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('numdocmili', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('disciplina', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.Column('jornada', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('banco', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('agencia_banco', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('conta_banco', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('pasep', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('data_exercicio', sa.Date(), nullable=True),
    sa.Column('dt_inicio', sa.Date(), nullable=True),
    sa.Column('dtdesligamento', sa.Date(), nullable=True),
    sa.Column('sg_unidade_honoraria_atual', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('sg_data_atualizacao_uh', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula', name='uq_funcionarios_matricula')
    )
    op.create_index(op.f('ix_funcionarios_cargo_id'), 'funcionarios', ['cargo_id'], unique=False)
    op.create_index(op.f('ix_funcionarios_matricula'), 'funcionarios', ['matricula'], unique=False)
    op.create_index(op.f('ix_funcionarios_setor_id'), 'funcionarios', ['setor_id'], unique=False)
    op.create_index(op.f('ix_funcionarios_upload_id'), 'funcionarios', ['upload_id'], unique=False)
    op.create_table('contatos_funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(length=180), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('validado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'tipo', name='uq_contatos_tipo')
    )
    op.create_index(op.f('ix_contatos_funcionario_funcionario_id'), 'contatos_funcionario', ['funcionario_id'], unique=False)
    op.create_table('documentos_funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False),
    sa.Column('uf', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('data_expedicao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('serdocmili', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('orgao', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('zona_titulo', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('secao_titulo', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('serie_cart_pro', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('categoria_cnh', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('cert_livro', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('cert_matricula', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('cert_folha', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('cert_cartorio', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('cartorio_municipio', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('uf_cartorio', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'tipo', name='uq_documentos_tipo')
    )
    op.create_index(op.f('ix_documentos_funcionario_funcionario_id'), 'documentos_funcionario', ['funcionario_id'], unique=False)
    op.create_table('enderecos_funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=155), nullable=True),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('complemento', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('uf', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'endereco', 'numero', 'complemento', name='uq_enderecos_funcionario_endereco')
    )
    op.create_index(op.f('ix_enderecos_funcionario_funcionario_id'), 'enderecos_funcionario', ['funcionario_id'], unique=False)
    op.create_table('honorarios_afastamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('matricula_planilha', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('nome_planilha', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('cargo_planilha', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('setor_planilha', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('nome_setor_planilha', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('sigla_planilha', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('dt_inicio', sa.Date(), nullable=True),
    sa.Column('dt_prevista', sa.Date(), nullable=True),
    sa.Column('dt_fim', sa.Date(), nullable=True),
    sa.Column('ini_ferias', sa.Date(), nullable=True),
    sa.Column('fim_ferias', sa.Date(), nullable=True),
    sa.Column('lei_ini', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('lei_fim', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('codfreq', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('freq_ini', sa.Date(), nullable=True),
    sa.Column('freq_fim', sa.Date(), nullable=True),
    sa.Column('vinculo', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.CheckConstraint('(dt_fim IS NULL) OR (dt_inicio <= dt_fim)', name='ck_afast_datas'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['honorarios_tipos_afastamento.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'dt_inicio', 'dt_fim', name='uq_afast_funcionario_inicio_fim_tipo')
    )
    op.create_index(op.f('ix_honorarios_afastamentos_funcionario_id'), 'honorarios_afastamentos', ['funcionario_id'], unique=False)
    op.create_index(op.f('ix_honorarios_afastamentos_tipo_id'), 'honorarios_afastamentos', ['tipo_id'], unique=False)
    op.create_index(op.f('ix_honorarios_afastamentos_upload_id'), 'honorarios_afastamentos', ['upload_id'], unique=False)
    op.create_table('logs_bcadastro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('nome_usuario', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('matricula_usuario', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('cpf_cnpj', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('acao', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('ip_origem', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_bcadastro_cpf_cnpj'), 'logs_bcadastro', ['cpf_cnpj'], unique=False)
    op.create_index(op.f('ix_logs_bcadastro_funcionario_id'), 'logs_bcadastro', ['funcionario_id'], unique=False)
    op.create_index(op.f('ix_logs_bcadastro_matricula_usuario'), 'logs_bcadastro', ['matricula_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_bcadastro_matricula_usuario'), table_name='logs_bcadastro')
    op.drop_index(op.f('ix_logs_bcadastro_funcionario_id'), table_name='logs_bcadastro')
    op.drop_index(op.f('ix_logs_bcadastro_cpf_cnpj'), table_name='logs_bcadastro')
    op.drop_table('logs_bcadastro')
    op.drop_index(op.f('ix_honorarios_afastamentos_upload_id'), table_name='honorarios_afastamentos')
    op.drop_index(op.f('ix_honorarios_afastamentos_tipo_id'), table_name='honorarios_afastamentos')
    op.drop_index(op.f('ix_honorarios_afastamentos_funcionario_id'), table_name='honorarios_afastamentos')
    op.drop_table('honorarios_afastamentos')
    op.drop_index(op.f('ix_enderecos_funcionario_funcionario_id'), table_name='enderecos_funcionario')
    op.drop_table('enderecos_funcionario')
    op.drop_index(op.f('ix_documentos_funcionario_funcionario_id'), table_name='documentos_funcionario')
    op.drop_table('documentos_funcionario')
    op.drop_index(op.f('ix_contatos_funcionario_funcionario_id'), table_name='contatos_funcionario')
    op.drop_table('contatos_funcionario')
    op.drop_index(op.f('ix_funcionarios_upload_id'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_setor_id'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_matricula'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_cargo_id'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_table('uploads')
    op.drop_table('setores')
    op.drop_index(op.f('ix_permissions_app'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('honorarios_tipos_afastamento')
    op.drop_index(op.f('ix_honorarios_calc_rules_escopo'), table_name='honorarios_calc_rules')
    op.drop_index(op.f('ix_honorarios_calc_rules_codigo_regra'), table_name='honorarios_calc_rules')
    op.drop_table('honorarios_calc_rules')
    op.drop_index(op.f('ix_honorarios_calc_audit_escopo'), table_name='honorarios_calc_audit')
    op.drop_table('honorarios_calc_audit')
    op.drop_table('health')
    op.drop_table('cargos')
    # ### end Alembic commands ###
