"""apagando tabela desnecessaria para acesso

Revision ID: a62bf85b6551
Revises: 10f619f9ebec
Create Date: 2025-11-04 14:37:42.384473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a62bf85b6551'
down_revision: Union[str, None] = '10f619f9ebec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aprovacoes_acesso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprovacoes_acesso',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('aprovador', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('justificativa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('solicitacao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_aprovacao', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_acesso.id'], name=op.f('aprovacoes_acesso_solicitacao_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('aprovacoes_acesso_pkey'))
    )
    # ### end Alembic commands ###
