"""adicionando nova data_exercicio

Revision ID: a80ecc5488d6
Revises: a5a21889ba51
Create Date: 2025-11-14 16:11:27.566366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a80ecc5488d6'
down_revision: Union[str, None] = 'a5a21889ba51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('data_exercicio_atual', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'data_exercicio_atual')
    # ### end Alembic commands ###
