"""atualizando model de cursos ofertas

Revision ID: 56bbb0e7e5ed
Revises: f66294e7249c
Create Date: 2025-12-10 13:51:45.163948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56bbb0e7e5ed'
down_revision: Union[str, None] = 'f66294e7249c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cursos_ofertas',
        sa.Column('inscritos_enviados', sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos_ofertas', 'inscritos_enviados')
    # ### end Alembic commands ###
