"""update regra add ativa

Revision ID: 32eb77219f38
Revises: 2ef86c356a95
Create Date: 2025-10-24 14:15:28.550897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32eb77219f38'
down_revision: Union[str, None] = '2ef86c356a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regra', sa.Column('ativa', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regra', 'ativa')
    # ### end Alembic commands ###
