"""mudando UH para possivel null

Revision ID: ccb6c03bb886
Revises: b637cbd94875
Create Date: 2025-10-17 11:58:23.153624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ccb6c03bb886'
down_revision: Union[str, None] = 'b637cbd94875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'sg_unidade_honoraria_atual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'sg_unidade_honoraria_atual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
