"""add data_referencia_calculo em folha de pagamentos

Revision ID: a4d5f090a2ea
Revises: 5742401530c8
Create Date: 2025-11-19 12:42:01.349553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4d5f090a2ea'
down_revision: Union[str, None] = '5742401530c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folhas_honorarios', sa.Column('data_referencia_calculo', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folhas_honorarios', 'data_referencia_calculo')
    # ### end Alembic commands ###
