"""mudando tabelas para acesso

Revision ID: 10f619f9ebec
Revises: b3e2aa0f1bda
Create Date: 2025-11-04 14:36:20.669957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10f619f9ebec'
down_revision: Union[str, None] = 'b3e2aa0f1bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes_acesso', sa.Column('aplicacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('solicitacoes_acesso', sa.Column('aprovador', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('solicitacoes_acesso', sa.Column('data_aprovacao', sa.Date(), nullable=True))
    op.drop_column('solicitacoes_acesso', 'sistema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes_acesso', sa.Column('sistema', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('solicitacoes_acesso', 'data_aprovacao')
    op.drop_column('solicitacoes_acesso', 'aprovador')
    op.drop_column('solicitacoes_acesso', 'aplicacao')
    # ### end Alembic commands ###
