"""corrigindo tipo de data_atualizacao_uh

Revision ID: 7ed20f4fdf82
Revises: e3abbb5bbae1
Create Date: 2025-10-14 13:28:47.223943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7ed20f4fdf82'
down_revision: Union[str, None] = 'e3abbb5bbae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'sg_unidade_honoraria_atual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('funcionarios', 'sg_data_atualizacao_uh',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'sg_data_atualizacao_uh',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('funcionarios', 'sg_unidade_honoraria_atual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
