"""corrigindo nome de UserRole

Revision ID: 1e7f5b821bbb
Revises: 67ca964b2946
Create Date: 2025-10-10 15:04:52.548980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e7f5b821bbb'
down_revision: Union[str, None] = '67ca964b2946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
