"""add: coluna caminho do arquivo

Revision ID: 98f6319924ec
Revises: 874672c1088a
Create Date: 2025-11-25 15:22:13.897480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98f6319924ec'
down_revision: Union[str, None] = '874672c1088a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('arquivo_path', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'arquivo_path')
    # ### end Alembic commands ###
