"""atualizando model de inscricoes

Revision ID: 342ac38814f4
Revises: 56bbb0e7e5ed
Create Date: 2025-12-10 14:28:36.361581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '342ac38814f4'
down_revision: Union[str, None] = '56bbb0e7e5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
