"""nova modelagem do banco

Revision ID: f66294e7249c
Revises: 1511cd1ba215
Create Date: 2025-12-09 15:57:06.402725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f66294e7249c'
down_revision: Union[str, None] = '1511cd1ba215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificados_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('curso_oferta_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['curso_oferta_id'], ['cursos_ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificados_template_curso_oferta_id'), 'certificados_template', ['curso_oferta_id'], unique=False)
    op.drop_index(op.f('ix_certificados_cursos_curso_oferta_id'), table_name='certificados_cursos')
    op.drop_index(op.f('ix_certificados_cursos_funcionario_id'), table_name='certificados_cursos')
    op.drop_table('certificados_cursos')
    op.add_column('cursos', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('cursos_ofertas', sa.Column('lista_espera_limite', sa.DateTime(), nullable=True))
    op.add_column('cursos_ofertas', sa.Column('nome_professor', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('cursos_ofertas', 'vagas_disponiveis')
    op.drop_column('cursos_ofertas', 'limite_lista_espera')
    op.add_column('inscricoes_cursos', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('inscricoes_cursos', sa.Column('data_emissao_certificado', sa.DateTime(), nullable=True))
    op.add_column('inscricoes_cursos', sa.Column('codigo_verificacao_certificado', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('lista_espera_cursos', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_unique_constraint(None, 'lista_espera_cursos', ['token_unico'])
    op.drop_column('lista_espera_cursos', 'expira_em')
    op.drop_column('lista_espera_cursos', 'ordem')
    op.add_column('presenca_cursos', sa.Column('validado', sa.Boolean(), nullable=False))
    op.drop_column('presenca_cursos', 'valido')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presenca_cursos', sa.Column('valido', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('presenca_cursos', 'validado')
    op.add_column('lista_espera_cursos', sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lista_espera_cursos', sa.Column('expira_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lista_espera_cursos', type_='unique')
    op.drop_column('lista_espera_cursos', 'email')
    op.drop_column('inscricoes_cursos', 'codigo_verificacao_certificado')
    op.drop_column('inscricoes_cursos', 'data_emissao_certificado')
    op.drop_column('inscricoes_cursos', 'email')
    op.add_column('cursos_ofertas', sa.Column('limite_lista_espera', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cursos_ofertas', sa.Column('vagas_disponiveis', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cursos_ofertas', 'nome_professor')
    op.drop_column('cursos_ofertas', 'lista_espera_limite')
    op.drop_column('cursos', 'slug')
    op.create_table('certificados_cursos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('curso_oferta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_emissao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('arquivo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_verificacao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['curso_oferta_id'], ['cursos_ofertas.id'], name=op.f('certificados_cursos_curso_oferta_id_fkey')),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('certificados_cursos_funcionario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certificados_cursos_pkey'))
    )
    op.create_index(op.f('ix_certificados_cursos_funcionario_id'), 'certificados_cursos', ['funcionario_id'], unique=False)
    op.create_index(op.f('ix_certificados_cursos_curso_oferta_id'), 'certificados_cursos', ['curso_oferta_id'], unique=False)
    op.drop_index(op.f('ix_certificados_template_curso_oferta_id'), table_name='certificados_template')
    op.drop_table('certificados_template')
    # ### end Alembic commands ###
