"""add titulo

Revision ID: 03169463e539
Revises: ca7134aad55d
Create Date: 2025-12-04 11:47:54.571386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03169463e539'
down_revision: Union[str, None] = 'ca7134aad55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('em aberto', 'andamento', 'concluído', 'improcedente', name='reportstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('em aberto', 'andamento', 'concluído', 'improcedente', name='reportstatus'),
               existing_nullable=True)
    op.drop_column('reports', 'titulo')
    # ### end Alembic commands ###
