"""corrigindo status

Revision ID: 54795368548a
Revises: ee14d1b49ad0
Create Date: 2025-11-11 13:52:44.160970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54795368548a'
down_revision: Union[str, None] = 'ee14d1b49ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'status',
               existing_type=postgresql.ENUM('ATIVO', 'APOSENTADO', 'OBITO', 'INATIVO', 'AFASTADO', 'CEDIDO', name='funcionariostatus'),
               type_=sa.Enum('ATIVO', 'APOSENTADO', 'OBITO', 'INATIVO', 'AFASTADO', 'CEDIDO', name='funcionario_status_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'status',
               existing_type=sa.Enum('ATIVO', 'APOSENTADO', 'OBITO', 'INATIVO', 'AFASTADO', 'CEDIDO', name='funcionario_status_enum', native_enum=False),
               type_=postgresql.ENUM('ATIVO', 'APOSENTADO', 'OBITO', 'INATIVO', 'AFASTADO', 'CEDIDO', name='funcionariostatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
