"""fix

Revision ID: 2282349dc5eb
Revises: bde571a493f4
Create Date: 2025-12-18 12:06:00.911516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2282349dc5eb'
down_revision: Union[str, None] = 'bde571a493f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lista_espera_cursos', sa.Column('data_envio_email', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lista_espera_cursos', 'data_envio_email')
    # ### end Alembic commands ###
