"""mudando modelo de afastamento

Revision ID: 927a7558b22b
Revises: bb9ce25eae4d
Create Date: 2025-10-13 17:10:49.643193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '927a7558b22b'
down_revision: Union[str, None] = 'bb9ce25eae4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honorarios_afastamentos', 'fim_ferias')
    op.drop_column('honorarios_afastamentos', 'setor_planilha')
    op.drop_column('honorarios_afastamentos', 'sigla_planilha')
    op.drop_column('honorarios_afastamentos', 'vinculo')
    op.drop_column('honorarios_afastamentos', 'cargo_planilha')
    op.drop_column('honorarios_afastamentos', 'ini_ferias')
    op.drop_column('honorarios_afastamentos', 'nome_setor_planilha')
    op.drop_column('honorarios_afastamentos', 'nome_planilha')
    op.drop_column('honorarios_afastamentos', 'matricula_planilha')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_afastamentos', sa.Column('matricula_planilha', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('honorarios_afastamentos', sa.Column('nome_planilha', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('honorarios_afastamentos', sa.Column('nome_setor_planilha', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('ini_ferias', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('cargo_planilha', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('honorarios_afastamentos', sa.Column('vinculo', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('sigla_planilha', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('setor_planilha', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('fim_ferias', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
