"""create_log

Revision ID: ec63ee30e8fe
Revises: b0238b79d48f
Create Date: 2025-12-18 14:15:48.126312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec63ee30e8fe'
down_revision: Union[str, None] = '2282349dc5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('application', sa.Enum('ACERVO', 'AUTOS_JUDICIAIS', name='logapplicationenum'), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'READ', name='logactionenum'), nullable=False),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.execute("DROP TYPE IF EXISTS logapplicationenum")
    op.execute("DROP TYPE IF EXISTS logactionenum")
    # ### end Alembic commands ###
