"""update aplicacao and perfil. add public and parent

Revision ID: 17e05270584c
Revises: 05d60dd3c074
Create Date: 2025-11-18 17:34:39.588188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17e05270584c'
down_revision: Union[str, None] = '05d60dd3c074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aplicacao', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('perfil', sa.Column('public', sa.Boolean(), nullable=True))
    op.execute("UPDATE aplicacao SET public = TRUE")
    op.execute("UPDATE perfil SET public = TRUE")
    op.alter_column('aplicacao', 'public', nullable=False)
    op.alter_column('perfil', 'public', nullable=False)
    
    op.add_column('perfil', sa.Column('extended_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'perfil', 'perfil', ['extended_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perfil', type_='foreignkey')
    op.drop_column('perfil', 'extended_id')
    op.drop_column('perfil', 'public')
    op.drop_column('aplicacao', 'public')
    # ### end Alembic commands ###
