"""mudando modelo de afastamentos

Revision ID: 7751670c1902
Revises: 388807473ed6
Create Date: 2025-10-14 12:15:53.002559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7751670c1902'
down_revision: Union[str, None] = '388807473ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_afastamentos', sa.Column('inicio', sa.Date(), nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('fim', sa.Date(), nullable=True))
    op.drop_constraint(op.f('uq_afast_funcionario_tipo_periodo'), 'honorarios_afastamentos', type_='unique')
    op.create_unique_constraint('uq_afast_funcionario_tipo_periodo', 'honorarios_afastamentos', ['funcionario_id', 'tipo_id', 'inicio', 'fim'])
    op.drop_column('honorarios_afastamentos', 'lei_ini')
    op.drop_column('honorarios_afastamentos', 'lei_fim')
    op.drop_column('honorarios_afastamentos', 'freq_fim')
    op.drop_column('honorarios_afastamentos', 'freq_ini')
    op.drop_column('honorarios_afastamentos', 'codfreq')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_afastamentos', sa.Column('codfreq', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('freq_ini', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('freq_fim', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('lei_fim', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('honorarios_afastamentos', sa.Column('lei_ini', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_afast_funcionario_tipo_periodo', 'honorarios_afastamentos', type_='unique')
    op.create_unique_constraint(op.f('uq_afast_funcionario_tipo_periodo'), 'honorarios_afastamentos', ['funcionario_id', 'tipo_id', 'lei_ini', 'lei_fim', 'freq_ini', 'freq_fim'], postgresql_nulls_not_distinct=False)
    op.drop_column('honorarios_afastamentos', 'fim')
    op.drop_column('honorarios_afastamentos', 'inicio')
    # ### end Alembic commands ###
