"""colocando periodo inicio e periodo fim em calculo auditoria

Revision ID: 0ddd26cdf888
Revises: a80ecc5488d6
Create Date: 2025-11-17 11:07:20.023065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ddd26cdf888'
down_revision: Union[str, None] = 'a80ecc5488d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_calculo_auditoria', sa.Column('inicio_periodo', sa.Date(), nullable=True))
    op.add_column('honorarios_calculo_auditoria', sa.Column('fim_periodo', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honorarios_calculo_auditoria', 'fim_periodo')
    op.drop_column('honorarios_calculo_auditoria', 'inicio_periodo')
    # ### end Alembic commands ###
