"""tirando parte de rh_report_message

Revision ID: 71a3f1510f40
Revises: 97294309583b
Create Date: 2025-12-01 11:01:29.938641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71a3f1510f40'
down_revision: Union[str, None] = '97294309583b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folhas_honorarios', 'rh_report_message')
    op.drop_column('folhas_honorarios', 'rh_reported_at')
    op.alter_column('notificacoes', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notificacoes', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.add_column('folhas_honorarios', sa.Column('rh_reported_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('folhas_honorarios', sa.Column('rh_report_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
