"""fix noificacoes

Revision ID: d2076dbb98ee
Revises: 0dbd553fe36d
Create Date: 2025-11-24 14:46:12.587314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2076dbb98ee'
down_revision: Union[str, None] = '0dbd553fe36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificacoes', sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_notificacoes_funcionario_id'), table_name='notificacoes')
    op.create_index(op.f('ix_notificacoes_matricula'), 'notificacoes', ['matricula'], unique=False)
    op.drop_constraint(op.f('notificacoes_funcionario_id_fkey'), 'notificacoes', type_='foreignkey')
    op.create_foreign_key(None, 'notificacoes', 'funcionarios', ['matricula'], ['matricula'])
    op.drop_column('notificacoes', 'funcionario_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificacoes', sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notificacoes', type_='foreignkey')
    op.create_foreign_key(op.f('notificacoes_funcionario_id_fkey'), 'notificacoes', 'funcionarios', ['funcionario_id'], ['id'])
    op.drop_index(op.f('ix_notificacoes_matricula'), table_name='notificacoes')
    op.create_index(op.f('ix_notificacoes_funcionario_id'), 'notificacoes', ['funcionario_id'], unique=False)
    op.drop_column('notificacoes', 'matricula')
    # ### end Alembic commands ###
