"""adicionando auditoria e apagando tabela antiga

Revision ID: 2f5d6c848717
Revises: 7ed20f4fdf82
Create Date: 2025-10-14 15:14:51.136979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f5d6c848717'
down_revision: Union[str, None] = '7ed20f4fdf82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honorarios_calculo_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('uh_anterior', sa.Float(), nullable=True),
    sa.Column('uh_nova', sa.Float(), nullable=False),
    sa.Column('data_calculo', sa.DateTime(), nullable=False),
    sa.Column('data_referencia', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honorarios_calculo_auditoria_funcionario_id'), 'honorarios_calculo_auditoria', ['funcionario_id'], unique=False)
    op.drop_index(op.f('ix_honorarios_calc_audit_escopo'), table_name='honorarios_calc_audit')
    op.drop_table('honorarios_calc_audit')
    op.drop_index(op.f('ix_honorarios_calc_rules_codigo_regra'), table_name='honorarios_calc_rules')
    op.drop_index(op.f('ix_honorarios_calc_rules_escopo'), table_name='honorarios_calc_rules')
    op.drop_table('honorarios_calc_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honorarios_calc_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('codigo_regra', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('escopo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('versao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prioridade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('active_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('condicao', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('acao', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('honorarios_calc_rules_pkey'))
    )
    op.create_index(op.f('ix_honorarios_calc_rules_escopo'), 'honorarios_calc_rules', ['escopo'], unique=False)
    op.create_index(op.f('ix_honorarios_calc_rules_codigo_regra'), 'honorarios_calc_rules', ['codigo_regra'], unique=False)
    op.create_table('honorarios_calc_audit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('escopo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('conteudo', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('regra_aplicada', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('honorarios_calc_audit_pkey'))
    )
    op.create_index(op.f('ix_honorarios_calc_audit_escopo'), 'honorarios_calc_audit', ['escopo'], unique=False)
    op.drop_index(op.f('ix_honorarios_calculo_auditoria_funcionario_id'), table_name='honorarios_calculo_auditoria')
    op.drop_table('honorarios_calculo_auditoria')
    # ### end Alembic commands ###
