"""criando status em funcionario

Revision ID: d4838eaeddf4
Revises: cf65c52ba16c
Create Date: 2025-11-06 20:17:58.871461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd4838eaeddf4'
down_revision: Union[str, None] = 'cf65c52ba16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'status')
    # ### end Alembic commands ###
