"""add perfil

Revision ID: 0c7db34b5a1d
Revises: 6e1769288277
Create Date: 2025-11-04 14:54:11.913438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c7db34b5a1d'
down_revision: Union[str, None] = '6e1769288277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes_acesso', sa.Column('perfil', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitacoes_acesso', 'perfil')
    # ### end Alembic commands ###
