"""fix slug out

Revision ID: b0238b79d48f
Revises: 55d51a360e19
Create Date: 2025-12-15 15:54:24.681629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b0238b79d48f'
down_revision: Union[str, None] = '55d51a360e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('slug', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
