"""create auth roles

Revision ID: 32d017ec7f31
Revises: 6d41e5a3b942
Create Date: 2025-10-21 17:21:12.161503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32d017ec7f31'
down_revision: Union[str, None] = '6d41e5a3b942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicacao_nome'), 'applicacao', ['nome'], unique=True)
    op.create_index(op.f('ix_applicacao_slug'), 'applicacao', ['slug'], unique=True)
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_nome'), 'perfil', ['nome'], unique=True)
    op.create_index(op.f('ix_perfil_slug'), 'perfil', ['slug'], unique=True)
    op.create_table('regra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('codigo_setor', sa.Integer(), nullable=False),
    sa.Column('codigo_cargo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regra')
    op.drop_index(op.f('ix_perfil_slug'), table_name='perfil')
    op.drop_index(op.f('ix_perfil_nome'), table_name='perfil')
    op.drop_table('perfil')
    op.drop_index(op.f('ix_applicacao_slug'), table_name='applicacao')
    op.drop_index(op.f('ix_applicacao_nome'), table_name='applicacao')
    op.drop_table('applicacao')
    # ### end Alembic commands ###
