"""criando enum

Revision ID: dc97f47d9500
Revises: 342ac38814f4
Create Date: 2025-12-11 10:40:41.106638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc97f47d9500'
down_revision: Union[str, None] = '342ac38814f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Primeiro, atualiza os dados existentes de string minúscula para UPPERCASE
    op.execute("UPDATE cursos_ofertas SET status = UPPER(status) WHERE status IS NOT NULL")
    
    # Depois altera o tipo da coluna para Enum
    op.alter_column('cursos_ofertas', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ABERTA', 'FECHADA', 'CANCELADA', name='cursos_ofertas_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cursos_ofertas', 'status',
               existing_type=sa.Enum('ABERTA', 'FECHADA', 'CANCELADA', name='cursos_ofertas_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
