"""mudando modelo de afastamento/codigo

Revision ID: 388807473ed6
Revises: 22882ab055b5
Create Date: 2025-10-13 17:50:55.407000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '388807473ed6'
down_revision: Union[str, None] = '22882ab055b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honorarios_afastamentos', 'codigo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_afastamentos', sa.Column('codigo', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
