"""adicionando codigo setor index

Revision ID: 6d41e5a3b942
Revises: 7ff3e0f76ae4
Create Date: 2025-10-21 15:37:33.014069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d41e5a3b942'
down_revision: Union[str, None] = '7ff3e0f76ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('setores_codigo_key'), 'setores', type_='unique')
    op.create_index(op.f('ix_setores_codigo'), 'setores', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setores_codigo'), table_name='setores')
    op.create_unique_constraint(op.f('setores_codigo_key'), 'setores', ['codigo'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
