"""fix auth unique

Revision ID: e63f6e15e3b6
Revises: 32eb77219f38
Create Date: 2025-10-24 18:01:52.593198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e63f6e15e3b6'
down_revision: Union[str, None] = '32eb77219f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aplicacao_nome'), table_name='aplicacao')
    op.drop_constraint(op.f('uq_aplicacao_slug'), 'aplicacao', type_='unique')
    op.drop_index(op.f('ix_perfil_nome'), table_name='perfil')
    op.drop_index(op.f('ix_perfil_slug'), table_name='perfil')
    op.create_index(op.f('ix_perfil_slug'), 'perfil', ['slug'], unique=False)
    op.create_index(op.f('ix_regra_codigo_cargo'), 'regra', ['codigo_cargo'], unique=False)
    op.create_index(op.f('ix_regra_codigo_setor'), 'regra', ['codigo_setor'], unique=False)
    op.create_index(op.f('ix_regra_matricula'), 'regra', ['matricula'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regra_matricula'), table_name='regra')
    op.drop_index(op.f('ix_regra_codigo_setor'), table_name='regra')
    op.drop_index(op.f('ix_regra_codigo_cargo'), table_name='regra')
    op.drop_index(op.f('ix_perfil_slug'), table_name='perfil')
    op.create_index(op.f('ix_perfil_slug'), 'perfil', ['slug'], unique=True)
    op.create_index(op.f('ix_perfil_nome'), 'perfil', ['nome'], unique=True)
    op.create_unique_constraint(op.f('uq_aplicacao_slug'), 'aplicacao', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_aplicacao_nome'), 'aplicacao', ['nome'], unique=True)
    # ### end Alembic commands ###
