"""adicionando tipo de alteracao

Revision ID: b637cbd94875
Revises: 2f5d6c848717
Create Date: 2025-10-14 15:17:50.653190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b637cbd94875'
down_revision: Union[str, None] = '2f5d6c848717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_calculo_auditoria', sa.Column('tipo_alteracao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honorarios_calculo_auditoria', 'tipo_alteracao')
    # ### end Alembic commands ###
