"""adicionando data_aposentadoria em funcionario

Revision ID: cf65c52ba16c
Revises: 0c7db34b5a1d
Create Date: 2025-11-05 14:15:11.350561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf65c52ba16c'
down_revision: Union[str, None] = '0c7db34b5a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('data_aposentadoria', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'data_aposentadoria')
    # ### end Alembic commands ###
