"""model acolhimento

Revision ID: 05d60dd3c074
Revises: 2a77c82315f2
Create Date: 2025-11-17 14:08:50.510726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05d60dd3c074'
down_revision: Union[str, None] = '2a77c82315f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_formulario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('finalizado', sa.Boolean(), nullable=False),
    sa.Column('andamento', sa.Boolean(), nullable=False),
    sa.Column('protocolo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('horario_finalizado', sa.DateTime(), nullable=True),
    sa.Column('horario_andamento', sa.DateTime(), nullable=True),
    sa.Column('excluido', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('funcionarios', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'ATIVO'::funcionariostatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'ATIVO'::funcionariostatus"))
    op.drop_table('chamado')
    # ### end Alembic commands ###
