"""adicionando data_cedido

Revision ID: 799b93345254
Revises: c5bcbfd6be84
Create Date: 2025-12-01 13:56:25.669313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '799b93345254'
down_revision: Union[str, None] = 'c5bcbfd6be84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('data_cedido', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'data_cedido')
    # ### end Alembic commands ###
