"""att

Revision ID: f5167ead99d2
Revises: e82968f8acc1
Create Date: 2025-10-30 13:43:02.359112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5167ead99d2'
down_revision: Union[str, None] = 'e82968f8acc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_histories', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('page_histories', sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('page_histories', 'title')
    op.add_column('pages', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('pages', sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('pages', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('pages', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pages', 'active')
    op.drop_column('pages', 'user')
    op.drop_column('pages', 'type')
    op.add_column('page_histories', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('page_histories', 'user')
    op.drop_column('page_histories', 'type')
    # ### end Alembic commands ###
