"""fix

Revision ID: f6c53900e252
Revises: 644d4718ad47
Create Date: 2025-12-15 13:03:55.180115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6c53900e252'
down_revision: Union[str, None] = '644d4718ad47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'lista_espera_cursos',
        sa.Column(
            'utilizado',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()  # 👈 ESSENCIAL
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lista_espera_cursos', 'utilizado')
    # ### end Alembic commands ###
