"""mudando atributo aprovador para nullable

Revision ID: 6e1769288277
Revises: a62bf85b6551
Create Date: 2025-11-04 14:43:57.069936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6e1769288277'
down_revision: Union[str, None] = 'a62bf85b6551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solicitacoes_acesso', 'aprovador',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solicitacoes_acesso', 'aprovador',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
