"""ajustando model de folha

Revision ID: c5bcbfd6be84
Revises: 71a3f1510f40
Create Date: 2025-12-01 11:20:49.092407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5bcbfd6be84'
down_revision: Union[str, None] = '71a3f1510f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) Adiciona como NULLABLE
    op.add_column(
        'folhas_honorarios',
        sa.Column('rh_report_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        'folhas_honorarios',
        sa.Column('rh_report_error', sa.Boolean(), nullable=True)  # <-- TEMPORARIAMENTE NULLABLE
    )

    # 2) Preenche valores existentes com False
    op.execute("UPDATE folhas_honorarios SET rh_report_error = FALSE WHERE rh_report_error IS NULL;")

    # 3) Trava NOT NULL depois de preenchido
    op.alter_column(
        'folhas_honorarios',
        'rh_report_error',
        nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folhas_honorarios', 'rh_report_error')
    op.drop_column('folhas_honorarios', 'rh_report_message')
    # ### end Alembic commands ###
