"""adicionando codigo setor unique

Revision ID: 7ff3e0f76ae4
Revises: 4ab02b3a850b
Create Date: 2025-10-21 15:36:49.700636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7ff3e0f76ae4'
down_revision: Union[str, None] = '4ab02b3a850b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_setores_nome_sigla'), 'setores', type_='unique')
    op.create_unique_constraint(None, 'setores', ['codigo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'setores', type_='unique')
    op.create_unique_constraint(op.f('uq_setores_nome_sigla'), 'setores', ['nome', 'sigla'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
