"""addDjos

Revision ID: f36460bdee7c
Revises: ba200bfc9c34
Create Date: 2025-10-08 15:43:50.930979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f36460bdee7c'
down_revision: Union[str, None] = 'ba200bfc9c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('djoretfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tamanho', sa.Float(), nullable=False),
    sa.Column('tipo_arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('djoretfiletipoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tipo_arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_processo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tribunal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('municipio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unidade_judiciaria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cod_agencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_autor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf_cnpj_autor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_reu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf_cnpj_reu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('especializada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['retfile_id'], ['djoretfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('djoretfiletipoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Numeric(), nullable=False),
    sa.Column('valor_total_juros', sa.Numeric(), nullable=False),
    sa.Column('valor_total_correcao', sa.Numeric(), nullable=False),
    sa.Column('valor_total_atualizado', sa.Numeric(), nullable=False),
    sa.Column('retfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['retfile_id'], ['djoretfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retfilecabecalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tipo_registro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remessa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idremessa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('digito', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['retfile_id'], ['djoretfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('djoretfiletipob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tipo_arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cod_banco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cod_agencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_deposito', sa.DateTime(), nullable=False),
    sa.Column('valor_principal', sa.Numeric(), nullable=False),
    sa.Column('juros', sa.Numeric(), nullable=False),
    sa.Column('correcao', sa.Numeric(), nullable=False),
    sa.Column('valor_atualizado', sa.Numeric(), nullable=False),
    sa.Column('valor_resgatado', sa.Numeric(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.Column('cod_controle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_evento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parcela', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retfiletipoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['retfiletipoa_id'], ['djoretfiletipoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('djoretfiletipob')
    op.drop_table('retfilecabecalho')
    op.drop_table('djoretfiletipoc')
    op.drop_table('djoretfiletipoa')
    op.drop_table('djoretfile')
    # ### end Alembic commands ###
