"""ajustando a tabela reports

Revision ID: 874672c1088a
Revises: fdcf3fd70bfe
Create Date: 2025-11-25 14:34:07.718918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '874672c1088a'
down_revision: Union[str, None] = 'fdcf3fd70bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('reports', sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.drop_index(op.f('ix_reports_matricula'), table_name='reports')
    op.create_index(op.f('ix_reports_usuario'), 'reports', ['usuario'], unique=False)
    op.drop_column('reports', 'matricula')
    op.drop_column('reports', 'nome_usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('nome_usuario', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('matricula', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_reports_usuario'), table_name='reports')
    op.create_index(op.f('ix_reports_matricula'), 'reports', ['matricula'], unique=False)
    op.drop_column('reports', 'usuario')
    op.drop_column('reports', 'descricao')
    # ### end Alembic commands ###
