"""addComprovantes

Revision ID: ba200bfc9c34
Revises: b3b09305fa4e
Create Date: 2025-10-08 14:17:02.206455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba200bfc9c34'
down_revision: Union[str, None] = 'b3b09305fa4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprovantes_de_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('dataMovimento', sa.DateTime(), nullable=True),
    sa.Column('dataBalancete', sa.DateTime(), nullable=True),
    sa.Column('agOrigem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipoMovimentacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numeroDocumento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Numeric(), nullable=False),
    sa.Column('complemento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numProcesso', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipoComprovante', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprovantes_de_pagamento')
    # ### end Alembic commands ###
