"""adicionando tipo aposentadoria

Revision ID: ea5e3be0c53b
Revises: d4838eaeddf4
Create Date: 2025-11-06 21:02:11.708955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ea5e3be0c53b'
down_revision: Union[str, None] = 'd4838eaeddf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('tipo_aposentadoria', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'tipo_aposentadoria')
    # ### end Alembic commands ###
