"""update aplicacoes

Revision ID: 7c1f7632e342
Revises: 2063073efd35
Create Date: 2025-10-23 11:28:31.394600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c1f7632e342'
down_revision: Union[str, None] = '2063073efd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_aplicacao_nome', 'aplicacao', ['nome'])
    op.create_unique_constraint('uq_aplicacao_slug', 'aplicacao', ['slug'])
    op.create_unique_constraint('uq_perfil_nome_aplicacao_id', 'perfil', ['nome', 'aplicacao_id'])
    op.create_unique_constraint('uq_perfil_slug_aplicacao_id', 'perfil', ['slug', 'aplicacao_id'])
    op.alter_column('regra', 'codigo_setor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('regra', 'codigo_cargo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('regra', 'matricula',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('regra', 'validade',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_unique_constraint('uq_regra_codigo_setor_codigo_cargo_matricula_perfil_id', 'regra', ['codigo_setor', 'codigo_cargo', 'matricula', 'perfil_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_regra_codigo_setor_codigo_cargo_matricula_perfil_id', 'regra', type_='unique')
    op.alter_column('regra', 'validade',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('regra', 'matricula',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('regra', 'codigo_cargo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('regra', 'codigo_setor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_perfil_slug_aplicacao_id', 'perfil', type_='unique')
    op.drop_constraint('uq_perfil_nome_aplicacao_id', 'perfil', type_='unique')
    op.drop_constraint('uq_aplicacao_slug', 'aplicacao', type_='unique')
    op.drop_constraint('uq_aplicacao_nome', 'aplicacao', type_='unique')
    # ### end Alembic commands ###
