"""adicionando parte de erro da folha em folhasHonorarios

Revision ID: b627c1da6861
Revises: a4d5f090a2ea
Create Date: 2025-11-24 12:34:57.077434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b627c1da6861'
down_revision: Union[str, None] = 'a4d5f090a2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folhas_honorarios', sa.Column('rh_report_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('folhas_honorarios', sa.Column('rh_reported_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folhas_honorarios', 'rh_reported_at')
    op.drop_column('folhas_honorarios', 'rh_report_message')
    # ### end Alembic commands ###
