"""mudando tipo_afastamento sem acento

Revision ID: 2a77c82315f2
Revises: 8d57449dffd1
Create Date: 2025-11-17 11:51:11.733100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a77c82315f2'
down_revision: Union[str, None] = '8d57449dffd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_tipos_afastamento', sa.Column('mnemonico', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('honorarios_tipos_afastamento', 'mnemônico')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_tipos_afastamento', sa.Column('mnemônico', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('honorarios_tipos_afastamento', 'mnemonico')
    # ### end Alembic commands ###
