"""adicionando cedido_area_juridica

Revision ID: ee14d1b49ad0
Revises: 95efe5b2d35a
Create Date: 2025-11-11 13:38:21.930845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee14d1b49ad0'
down_revision: Union[str, None] = '95efe5b2d35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('cedido_area_juridica', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'cedido_area_juridica')
    # ### end Alembic commands ###
