"""addCabecalhos

Revision ID: b54a16490ecd
Revises: f36460bdee7c
Create Date: 2025-10-08 15:52:05.488601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b54a16490ecd'
down_revision: Union[str, None] = 'f36460bdee7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('djoretfilecabecalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tipo_registro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remessa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idremessa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('digito', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['retfile_id'], ['djoretfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('retfilecabecalho')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retfilecabecalho',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tipo_registro', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo_arquivo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remessa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idremessa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('digito', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retfile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['retfile_id'], ['djoretfile.id'], name=op.f('retfilecabecalho_retfile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('retfilecabecalho_pkey'))
    )
    op.drop_table('djoretfilecabecalho')
    # ### end Alembic commands ###
