"""fix lista de espera

Revision ID: 55d51a360e19
Revises: f6c53900e252
Create Date: 2025-12-15 13:11:24.807031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55d51a360e19'
down_revision: Union[str, None] = 'f6c53900e252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lista_espera_cursos_token_confirmacao_key'), 'lista_espera_cursos', type_='unique')
    op.drop_column('lista_espera_cursos', 'confirmado')
    op.drop_column('lista_espera_cursos', 'data_expiracao_token')
    op.drop_column('lista_espera_cursos', 'token_confirmacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lista_espera_cursos', sa.Column('token_confirmacao', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('lista_espera_cursos', sa.Column('data_expiracao_token', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('lista_espera_cursos', sa.Column('confirmado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('lista_espera_cursos_token_confirmacao_key'), 'lista_espera_cursos', ['token_confirmacao'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
