"""update aplicacao add global users

Revision ID: ee93985cd5ca
Revises: e63f6e15e3b6
Create Date: 2025-10-27 17:03:14.225085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee93985cd5ca'
down_revision: Union[str, None] = 'e63f6e15e3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aplicacao', sa.Column('global_users', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aplicacao', 'global_users')
    # ### end Alembic commands ###
