"""adicionando tabelas cursos

Revision ID: f87563a18398
Revises: 6dcde409114b
Create Date: 2025-12-09 14:44:12.649727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f87563a18398'
down_revision: Union[str, None] = '6dcde409114b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imagem_destaque', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos_ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('presencial', sa.Boolean(), nullable=False),
    sa.Column('link_reuniao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('local', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('vagas_totais', sa.Integer(), nullable=False),
    sa.Column('vagas_disponiveis', sa.Integer(), nullable=True),
    sa.Column('data_inicio_presenca', sa.DateTime(), nullable=True),
    sa.Column('data_fim_presenca', sa.DateTime(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('data_hora_max_inscricao', sa.DateTime(), nullable=True),
    sa.Column('limite_lista_espera', sa.DateTime(), nullable=True),
    sa.Column('data_inicio_liberacao', sa.DateTime(), nullable=True),
    sa.Column('data_fim_liberacao', sa.DateTime(), nullable=True),
    sa.Column('qr_presenca_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('certificado_modelo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_ofertas_curso_id'), 'cursos_ofertas', ['curso_id'], unique=False)
    op.create_table('certificados_cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('curso_oferta_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('arquivo_id', sa.Integer(), nullable=False),
    sa.Column('codigo_verificacao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['curso_oferta_id'], ['cursos_ofertas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificados_cursos_curso_oferta_id'), 'certificados_cursos', ['curso_oferta_id'], unique=False)
    op.create_index(op.f('ix_certificados_cursos_funcionario_id'), 'certificados_cursos', ['funcionario_id'], unique=False)
    op.create_table('inscricoes_cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('curso_oferta_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.Column('cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_cancelamento', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['curso_oferta_id'], ['cursos_ofertas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscricoes_cursos_curso_oferta_id'), 'inscricoes_cursos', ['curso_oferta_id'], unique=False)
    op.create_index(op.f('ix_inscricoes_cursos_funcionario_id'), 'inscricoes_cursos', ['funcionario_id'], unique=False)
    op.create_table('lista_espera_cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('curso_oferta_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('token_unico', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('utilizado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['curso_oferta_id'], ['cursos_ofertas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lista_espera_cursos_curso_oferta_id'), 'lista_espera_cursos', ['curso_oferta_id'], unique=False)
    op.create_index(op.f('ix_lista_espera_cursos_funcionario_id'), 'lista_espera_cursos', ['funcionario_id'], unique=False)
    op.create_table('presenca_cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('curso_oferta_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('latitude', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('longitude', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('distancia_metros', sa.Float(), nullable=True),
    sa.Column('valido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['curso_oferta_id'], ['cursos_ofertas.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presenca_cursos_curso_oferta_id'), 'presenca_cursos', ['curso_oferta_id'], unique=False)
    op.create_index(op.f('ix_presenca_cursos_funcionario_id'), 'presenca_cursos', ['funcionario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presenca_cursos_funcionario_id'), table_name='presenca_cursos')
    op.drop_index(op.f('ix_presenca_cursos_curso_oferta_id'), table_name='presenca_cursos')
    op.drop_table('presenca_cursos')
    op.drop_index(op.f('ix_lista_espera_cursos_funcionario_id'), table_name='lista_espera_cursos')
    op.drop_index(op.f('ix_lista_espera_cursos_curso_oferta_id'), table_name='lista_espera_cursos')
    op.drop_table('lista_espera_cursos')
    op.drop_index(op.f('ix_inscricoes_cursos_funcionario_id'), table_name='inscricoes_cursos')
    op.drop_index(op.f('ix_inscricoes_cursos_curso_oferta_id'), table_name='inscricoes_cursos')
    op.drop_table('inscricoes_cursos')
    op.drop_index(op.f('ix_certificados_cursos_funcionario_id'), table_name='certificados_cursos')
    op.drop_index(op.f('ix_certificados_cursos_curso_oferta_id'), table_name='certificados_cursos')
    op.drop_table('certificados_cursos')
    op.drop_index(op.f('ix_cursos_ofertas_curso_id'), table_name='cursos_ofertas')
    op.drop_table('cursos_ofertas')
    op.drop_table('cursos')
    # ### end Alembic commands ###
