"""fix

Revision ID: 644d4718ad47
Revises: fix_invalid_status_ofertas
Create Date: 2025-12-15 13:02:06.887429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '644d4718ad47'
down_revision: Union[str, None] = 'fix_invalid_status_ofertas'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'lista_espera_cursos',
        sa.Column(
            'token_confirmacao',
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True
        )
    )

    op.add_column(
        'lista_espera_cursos',
        sa.Column(
            'data_expiracao_token',
            sa.DateTime(),
            nullable=True
        )
    )

    op.add_column(
        'lista_espera_cursos',
        sa.Column(
            'confirmado',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()  # 🔥 resolve o erro
        )
    )

    op.create_unique_constraint(
        None,
        'lista_espera_cursos',
        ['token_confirmacao']
    )

    op.drop_column('lista_espera_cursos', 'utilizado')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lista_espera_cursos', sa.Column('utilizado', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lista_espera_cursos', type_='unique')
    op.drop_column('lista_espera_cursos', 'confirmado')
    op.drop_column('lista_espera_cursos', 'data_expiracao_token')
    op.drop_column('lista_espera_cursos', 'token_confirmacao')
    # ### end Alembic commands ###
