"""alterando acesso

Revision ID: b3e2aa0f1bda
Revises: 0635e3c152f7
Create Date: 2025-11-04 14:26:20.380059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3e2aa0f1bda'
down_revision: Union[str, None] = '0635e3c152f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aprovacoes_acesso', sa.Column('solicitacao_id', sa.Integer(), nullable=False))
    op.add_column('aprovacoes_acesso', sa.Column('data_aprovacao', sa.Date(), nullable=True))
    op.drop_constraint(op.f('aprovacoes_acesso_solicitacaoId_fkey'), 'aprovacoes_acesso', type_='foreignkey')
    op.create_foreign_key(None, 'aprovacoes_acesso', 'solicitacoes_acesso', ['solicitacao_id'], ['id'])
    op.drop_column('aprovacoes_acesso', 'solicitacaoId')
    op.drop_column('aprovacoes_acesso', 'dataAprovacao')
    op.drop_column('solicitacoes_acesso', 'dataCriacao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitacoes_acesso', sa.Column('dataCriacao', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('aprovacoes_acesso', sa.Column('dataAprovacao', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('aprovacoes_acesso', sa.Column('solicitacaoId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'aprovacoes_acesso', type_='foreignkey')
    op.create_foreign_key(op.f('aprovacoes_acesso_solicitacaoId_fkey'), 'aprovacoes_acesso', 'solicitacoes_acesso', ['solicitacaoId'], ['id'])
    op.drop_column('aprovacoes_acesso', 'data_aprovacao')
    op.drop_column('aprovacoes_acesso', 'solicitacao_id')
    # ### end Alembic commands ###
