"""adicionando cedido_area_juridica editando

Revision ID: b0281fba1573
Revises: 54795368548a
Create Date: 2025-11-11 14:01:46.212619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b0281fba1573'
down_revision: Union[str, None] = '54795368548a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Define um valor padrão temporário para os nulos existentes
    op.execute("UPDATE funcionarios SET cedido_area_juridica = FALSE WHERE cedido_area_juridica IS NULL;")

    # Agora pode aplicar o NOT NULL
    op.alter_column(
        'funcionarios',
        'cedido_area_juridica',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funcionarios', 'cedido_area_juridica',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
