"""adicionando campo ativa

Revision ID: bb9ce25eae4d
Revises: 1e7f5b821bbb
Create Date: 2025-10-13 12:19:12.054525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb9ce25eae4d'
down_revision: Union[str, None] = '1e7f5b821bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_groups', sa.Column('ativa', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('permissions', sa.Column('ativa', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('roles', sa.Column('ativa', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'ativa')
    op.drop_column('permissions', 'ativa')
    op.drop_column('ad_groups', 'ativa')
    # ### end Alembic commands ###
