"""adicionando afastamento ate em funcionario

Revision ID: 95efe5b2d35a
Revises: e307805ee818
Create Date: 2025-11-07 14:58:36.807984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95efe5b2d35a'
down_revision: Union[str, None] = 'e307805ee818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('afastado_ate', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'afastado_ate')
    # ### end Alembic commands ###
