"""adicionando descricao em auditoria de calculos

Revision ID: 9d9fcc592319
Revises: 50ea640da023
Create Date: 2025-10-21 14:34:01.736859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d9fcc592319'
down_revision: Union[str, None] = '50ea640da023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_calculo_auditoria', sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honorarios_calculo_auditoria', 'descricao')
    # ### end Alembic commands ###
