"""update_logs

Revision ID: c107819222a6
Revises: 0871ba9ac570
Create Date: 2026-01-08 15:08:20.022522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c107819222a6'
down_revision: Union[str, None] = '0871ba9ac570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('newData', sa.JSON(), nullable=False))
    op.add_column('logs', sa.Column('oldData', sa.JSON(), nullable=False))
    # ### end Alembic commands ###
    # pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'oldData')
    op.drop_column('logs', 'newData')
    # ### end Alembic commands ###
