"""add-afastamento-orgao-juridico

Revision ID: 5dae076b2038
Revises: 812388507070
Create Date: 2026-01-27 17:41:46.854536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5dae076b2038'
down_revision: Union[str, None] = '812388507070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('honorarios_afastamentos', sa.Column('orgao_juridico', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('honorarios_afastamentos', 'orgao_juridico')
    # ### end Alembic commands ###
