"""log_bcadastro

Revision ID: bd83972a3ab5
Revises: abcdef123456
Create Date: 2026-01-09 16:19:30.140067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bd83972a3ab5"
down_revision: Union[str, None] = "abcdef123456"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "logs", sa.Column("response", postgresql.JSON(astext_type=sa.Text()), nullable=True, server_default="{}")
    )
    op.execute("ALTER TYPE logapplicationenum ADD VALUE IF NOT EXISTS 'BCADASTRO';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("logs", "response")
    # Nota: PostgreSQL não permite remover valores de enums diretamente.
    # Para remover 'BCADASTRO', seria necessário recriar o enum completo,
    # o que é complexo e pode causar problemas com dados existentes.
    # Portanto, o downgrade não remove o valor do enum.
    # ### end Alembic commands ###
