"""colunas de minuta e peticao

Revision ID: 7895647948f3
Revises: c8d9e0f1a2b3
Create Date: 2026-09-08 14:10:19.468336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7895647948f3'
down_revision: Union[str, None] = 'c8d9e0f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistente_ia_conversas', sa.Column('neo_id_minuta', sa.Integer(), nullable=True))
    op.add_column('assistente_ia_conversas', sa.Column('neo_id_peticao', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_assistente_ia_logs_user_chat_created'), table_name='assistente_ia_logs')

    # Há linhas legadas com inicio > fim; a constraint só pode ser criada depois
    # de corrigir esses registros (inverte as datas invertidas).
    op.execute(
        """
        UPDATE honorarios_afastamentos
        SET inicio = fim, fim = inicio
        WHERE inicio IS NOT NULL
          AND fim IS NOT NULL
          AND inicio > fim
        """
    )
    op.create_check_constraint(
        'ck_afast_datas_validas',
        'honorarios_afastamentos',
        '(inicio IS NULL OR fim IS NULL OR inicio <= fim)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_afast_datas_validas', 'honorarios_afastamentos', type_='check')
    op.create_index(op.f('ix_assistente_ia_logs_user_chat_created'), 'assistente_ia_logs', ['usuario_matricula', 'openwebui_chat_id', 'created_at'], unique=False)
    op.drop_column('assistente_ia_conversas', 'neo_id_peticao')
    op.drop_column('assistente_ia_conversas', 'neo_id_minuta')
    # ### end Alembic commands ###
