"""add_recebe_honorarios

Revision ID: c44d9da4e86e
Revises: 5dae076b2038
Create Date: 2026-02-25 09:32:29.670135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c44d9da4e86e'
down_revision: Union[str, None] = '5dae076b2038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('recebe_honorarios', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'recebe_honorarios')
    # ### end Alembic commands ###
