"""refatorando aula e oferta

Revision ID: 812388507070
Revises: 6858a66fe1b3
Create Date: 2026-01-12 12:48:12.433984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "812388507070"
down_revision: Union[str, None] = "6858a66fe1b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Primeiro adicionar as colunas à tabela aula
    op.add_column("aula", sa.Column("data_hora_inicio", sa.DateTime(), nullable=False))
    op.add_column("aula", sa.Column("data_hora_fim", sa.DateTime(), nullable=False))
    op.add_column("aula", sa.Column("presencial", sa.Boolean(), nullable=False))
    op.add_column("aula", sa.Column("nome_professor", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column("aula", sa.Column("link_reuniao", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column("aula", sa.Column("qr_presenca_token", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column("aula", sa.Column("data_inicio_presenca", sa.DateTime(), nullable=True))
    op.add_column("aula", sa.Column("data_fim_presenca", sa.DateTime(), nullable=True))

    # 2. Remover colunas antigas de aula
    op.drop_column("aula", "professor")
    op.drop_column("aula", "modalidade")
    op.drop_column("aula", "data")

    # 3. Remover colunas de cursos_ofertas que agora estão em aula
    op.drop_column("cursos_ofertas", "data_hora_inicio")
    op.drop_column("cursos_ofertas", "local")
    op.drop_column("cursos_ofertas", "link_reuniao")
    op.drop_column("cursos_ofertas", "presencial")
    op.drop_column("cursos_ofertas", "data_fim_presenca")
    op.drop_column("cursos_ofertas", "nome_professor")
    op.drop_column("cursos_ofertas", "data_inicio_presenca")
    op.drop_column("cursos_ofertas", "qr_presenca_token")
    op.drop_column("cursos_ofertas", "data_hora_fim")

    # 4. Adicionar coluna aula_id como nullable primeiro
    op.add_column("presenca_cursos", sa.Column("aula_id", sa.Integer(), nullable=True))

    # 5. Preencher aula_id baseado no curso_oferta_id
    # Para cada presenca_cursos, encontrar uma aula da mesma oferta
    op.execute(
        """
        UPDATE presenca_cursos pc
        SET aula_id = (
            SELECT a.id FROM aula a 
            WHERE a.oferta_id = pc.curso_oferta_id
            LIMIT 1
        )
        WHERE aula_id IS NULL AND curso_oferta_id IS NOT NULL;
    """
    )

    # 6. Se não houver aulas para algumas presenças, criar aulas padrão
    op.execute(
        """
        INSERT INTO aula (oferta_id, numero_aula, data_hora_inicio, data_hora_fim, presencial, created_at, updated_at)
        SELECT DISTINCT 
            pc.curso_oferta_id,
            1,
            NOW(),
            NOW() + INTERVAL '1 hour',
            true,
            NOW(),
            NOW()
        FROM presenca_cursos pc
        WHERE pc.aula_id IS NULL
        ON CONFLICT DO NOTHING;
    """
    )

    # 7. Atualizar novamente as presenças que ficaram sem aula_id
    op.execute(
        """
        UPDATE presenca_cursos pc
        SET aula_id = (
            SELECT a.id FROM aula a 
            WHERE a.oferta_id = pc.curso_oferta_id
            LIMIT 1
        )
        WHERE aula_id IS NULL AND curso_oferta_id IS NOT NULL;
    """
    )

    # 8. Agora alterar para NOT NULL
    op.alter_column("presenca_cursos", "aula_id", nullable=False)

    # 9. Remover a coluna curso_oferta_id e indexes
    op.drop_index(op.f("ix_presenca_cursos_curso_oferta_id"), table_name="presenca_cursos")
    op.drop_constraint(op.f("presenca_cursos_curso_oferta_id_fkey"), "presenca_cursos", type_="foreignkey")
    op.drop_column("presenca_cursos", "curso_oferta_id")

    # 10. Criar index e foreign key para aula_id
    op.create_index(op.f("ix_presenca_cursos_aula_id"), "presenca_cursos", ["aula_id"], unique=False)
    op.create_foreign_key(None, "presenca_cursos", "aula", ["aula_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("presenca_cursos", sa.Column("curso_oferta_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "presenca_cursos", type_="foreignkey")
    op.create_foreign_key(
        op.f("presenca_cursos_curso_oferta_id_fkey"), "presenca_cursos", "cursos_ofertas", ["curso_oferta_id"], ["id"]
    )
    op.drop_index(op.f("ix_presenca_cursos_aula_id"), table_name="presenca_cursos")
    op.create_index(op.f("ix_presenca_cursos_curso_oferta_id"), "presenca_cursos", ["curso_oferta_id"], unique=False)
    op.drop_column("presenca_cursos", "aula_id")
    op.add_column(
        "cursos_ofertas", sa.Column("data_hora_fim", postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "cursos_ofertas", sa.Column("qr_presenca_token", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.add_column(
        "cursos_ofertas", sa.Column("data_inicio_presenca", postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "cursos_ofertas", sa.Column("nome_professor", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.add_column(
        "cursos_ofertas", sa.Column("data_fim_presenca", postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.add_column("cursos_ofertas", sa.Column("presencial", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column(
        "cursos_ofertas", sa.Column("link_reuniao", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.add_column("cursos_ofertas", sa.Column("local", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(
        "cursos_ofertas", sa.Column("data_hora_inicio", postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.add_column("aula", sa.Column("data", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column("aula", sa.Column("modalidade", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column("aula", sa.Column("professor", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column("aula", "data_fim_presenca")
    op.drop_column("aula", "data_inicio_presenca")
    op.drop_column("aula", "qr_presenca_token")
    op.drop_column("aula", "link_reuniao")
    op.drop_column("aula", "nome_professor")
    op.drop_column("aula", "presencial")
    op.drop_column("aula", "data_hora_fim")
    op.drop_column("aula", "data_hora_inicio")
    # ### end Alembic commands ###
