"""update: spot-files. exists file

Revision ID: 415991474f11
Revises: 4579992220e6
Create Date: 2026-04-01 17:49:28.438559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '415991474f11'
down_revision: Union[str, None] = '4579992220e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot_files', sa.Column('is_mapped', sa.Boolean(), nullable=False))
    op.add_column('spot_files', sa.Column('is_indexed', sa.Boolean(), nullable=False))
    op.add_column('spot_files', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('spot_files', 'indexed')
    op.drop_column('spot_files', 'mapped')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot_files', sa.Column('mapped', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('spot_files', sa.Column('indexed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('spot_files', 'is_verified')
    op.drop_column('spot_files', 'is_indexed')
    op.drop_column('spot_files', 'is_mapped')
    # ### end Alembic commands ###
