"""update spot

Revision ID: e0778b4b5637
Revises: 46cbb1718d85
Create Date: 2026-04-20 17:14:30.069404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0778b4b5637'
down_revision: Union[str, None] = '46cbb1718d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acervo_indexador_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_directory', sa.Boolean(), nullable=False),
    sa.Column('is_mapped', sa.Boolean(), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=False),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['acervo_indexador_files.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['acervo_indexador_folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acervo_indexador_files_extension'), 'acervo_indexador_files', ['extension'], unique=False)
    op.create_index(op.f('ix_acervo_indexador_files_father_id'), 'acervo_indexador_files', ['father_id'], unique=False)
    op.create_index(op.f('ix_acervo_indexador_files_path'), 'acervo_indexador_files', ['path'], unique=True)
    op.create_index(op.f('ix_acervo_indexador_files_root_id'), 'acervo_indexador_files', ['root_id'], unique=False)
    op.drop_index(op.f('ix_spot_files_extension'), table_name='spot_files')
    op.drop_index(op.f('ix_spot_files_father_id'), table_name='spot_files')
    op.drop_index(op.f('ix_spot_files_path'), table_name='spot_files')
    op.drop_table('spot_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_directory', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('father_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_mapped', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_indexed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['father_id'], ['spot_files.id'], name=op.f('spot_files_father_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('spot_files_pkey'))
    )
    op.create_index(op.f('ix_spot_files_path'), 'spot_files', ['path'], unique=True)
    op.create_index(op.f('ix_spot_files_father_id'), 'spot_files', ['father_id'], unique=False)
    op.create_index(op.f('ix_spot_files_extension'), 'spot_files', ['extension'], unique=False)
    op.drop_index(op.f('ix_acervo_indexador_files_root_id'), table_name='acervo_indexador_files')
    op.drop_index(op.f('ix_acervo_indexador_files_path'), table_name='acervo_indexador_files')
    op.drop_index(op.f('ix_acervo_indexador_files_father_id'), table_name='acervo_indexador_files')
    op.drop_index(op.f('ix_acervo_indexador_files_extension'), table_name='acervo_indexador_files')
    op.drop_table('acervo_indexador_files')
    # ### end Alembic commands ###
