"""remove indexador files

Revision ID: 347a4b1813c0
Revises: e0778b4b5637
Create Date: 2026-04-20 17:27:49.415471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '347a4b1813c0'
down_revision: Union[str, None] = 'e0778b4b5637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acervo_indexador_files_extension'), table_name='acervo_indexador_files')
    op.drop_index(op.f('ix_acervo_indexador_files_father_id'), table_name='acervo_indexador_files')
    op.drop_index(op.f('ix_acervo_indexador_files_path'), table_name='acervo_indexador_files')
    op.drop_index(op.f('ix_acervo_indexador_files_root_id'), table_name='acervo_indexador_files')
    op.drop_table('acervo_indexador_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acervo_indexador_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_directory', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_mapped', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_indexed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('root_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('father_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['acervo_indexador_files.id'], name=op.f('acervo_indexador_files_father_id_fkey')),
    sa.ForeignKeyConstraint(['root_id'], ['acervo_indexador_folder.id'], name=op.f('acervo_indexador_files_root_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('acervo_indexador_files_pkey'))
    )
    op.create_index(op.f('ix_acervo_indexador_files_root_id'), 'acervo_indexador_files', ['root_id'], unique=False)
    op.create_index(op.f('ix_acervo_indexador_files_path'), 'acervo_indexador_files', ['path'], unique=True)
    op.create_index(op.f('ix_acervo_indexador_files_father_id'), 'acervo_indexador_files', ['father_id'], unique=False)
    op.create_index(op.f('ix_acervo_indexador_files_extension'), 'acervo_indexador_files', ['extension'], unique=False)
    # ### end Alembic commands ###
