"""Criando tabela de Configuracoes do Sistema

Revision ID: 2edf7ab1b4c2
Revises: 7d99519d923a
Create Date: 2026-05-25 12:44:21.469726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2edf7ab1b4c2'
down_revision: Union[str, None] = '7d99519d923a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
