"""update AcervoIndexFolder

Revision ID: 3cec4a6097b2
Revises: 347a4b1813c0
Create Date: 2026-04-22 17:39:21.723146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3cec4a6097b2'
down_revision: Union[str, None] = '347a4b1813c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acervo_indexador_folder', sa.Column('email_inexistente_enviado', sa.Boolean(), nullable=True))
    op.execute("UPDATE acervo_indexador_folder SET email_inexistente_enviado = FALSE")
    op.alter_column('acervo_indexador_folder', 'email_inexistente_enviado', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acervo_indexador_folder', 'email_inexistente_enviado')
    # ### end Alembic commands ###
