"""Criando a tabela de atas

Revision ID: 744b833bf40e
Revises: 91f938e52796
Create Date: 2026-04-01 11:14:20.193383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '744b833bf40e'
down_revision: Union[str, None] = '91f938e52796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('data_reuniao', sa.Date(), nullable=False),
    sa.Column('assuntos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('documento_nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('documento_bucket_group_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('documento_bucket_file_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atas')
    # ### end Alembic commands ###
