"""create_aula_table

Revision ID: abcdef123456
Revises: 0871ba9ac570
Create Date: 2026-01-09 14:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abcdef123456'
down_revision: Union[str, None] = '51681ee81b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('numero_aula', sa.Integer(), nullable=False),
    sa.Column('professor', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('local', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('modalidade', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['cursos_ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aula_oferta_id'), 'aula', ['oferta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aula_oferta_id'), table_name='aula')
    op.drop_table('aula')
    # ### end Alembic commands ###
    # pass