"""update cron

Revision ID: 46cbb1718d85
Revises: c24af5a76ca9
Create Date: 2026-04-16 15:16:19.597605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46cbb1718d85'
down_revision: Union[str, None] = 'c24af5a76ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crons_id'), 'crons', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crons_id'), table_name='crons')
    # ### end Alembic commands ###
