"""add nova coluna a presenca

Revision ID: 91f938e52796
Revises: 1c0c8ec2ff07
Create Date: 2026-03-02 17:05:07.462723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91f938e52796'
down_revision: Union[str, None] = '1c0c8ec2ff07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presenca_cursos', sa.Column('pgm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presenca_cursos', 'pgm')
    # ### end Alembic commands ###
