"""create indexador acervo

Revision ID: 0bb141805db7
Revises: cb4b888a4c71
Create Date: 2026-04-13 13:16:20.830812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bb141805db7'
down_revision: Union[str, None] = 'cb4b888a4c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acervo_indexador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ultima_indexacao', sa.DateTime(), nullable=True),
    sa.Column('cron_atualizacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cron_backup', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('acervo_indexador_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_backup', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ultima_indexacao_start', sa.DateTime(), nullable=True),
    sa.Column('ultima_indexacao_end', sa.DateTime(), nullable=True),
    sa.Column('acervo_indexador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acervo_indexador_id'], ['acervo_indexador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('logs', 'application',
               existing_type=postgresql.ENUM('ACERVO', 'AUTOS_JUDICIAIS', 'PUBLIC_UPLOAD', 'BCADASTRO', 'CURSOS', 'ATAS', name='logapplicationenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('logs', 'action',
               existing_type=postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', 'READ', name='logactionenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'action',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', 'READ', name='logactionenum'),
               existing_nullable=False)
    op.alter_column('logs', 'application',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('ACERVO', 'AUTOS_JUDICIAIS', 'PUBLIC_UPLOAD', 'BCADASTRO', 'CURSOS', 'ATAS', name='logapplicationenum'),
               existing_nullable=False)
    op.drop_table('acervo_indexador_folder')
    op.drop_table('acervo_indexador')
    # ### end Alembic commands ###
