"""acervo index update model

Revision ID: 9133c0a4f529
Revises: eb58b7baf29f
Create Date: 2026-04-15 15:27:05.675951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9133c0a4f529"
down_revision: Union[str, None] = "eb58b7baf29f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("acervo_indexador", sa.Column("ativo", sa.Boolean()))
    op.execute("UPDATE acervo_indexador SET ativo = TRUE")
    op.alter_column("acervo_indexador", "ativo", nullable=False)
    op.add_column("acervo_indexador_folder", sa.Column("ativo", sa.Boolean()))
    op.execute("UPDATE acervo_indexador_folder SET ativo = TRUE")
    op.alter_column("acervo_indexador_folder", "ativo", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("acervo_indexador_folder", "ativo")
    op.drop_column("acervo_indexador", "ativo")
    # ### end Alembic commands ###
