"""log_cursos

Revision ID: 6858a66fe1b3
Revises: bd83972a3ab5
Create Date: 2026-01-09 16:59:58.435715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6858a66fe1b3"
down_revision: Union[str, None] = "bd83972a3ab5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "logs",
        "response",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.execute("ALTER TYPE logapplicationenum ADD VALUE IF NOT EXISTS 'CURSOS';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "logs",
        "response",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::json"),
    )
    # Nota: PostgreSQL não permite remover valores de enums diretamente.
    # Para remover 'CURSOS', seria necessário recriar o enum completo,
    # o que é complexo e pode causar problemas com dados existentes.
    # Portanto, o downgrade não remove o valor do enum.
    # ### end Alembic commands ###
