"""spot-files

Revision ID: f05745d63331
Revises: 744b833bf40e
Create Date: 2026-04-01 15:39:47.941508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f05745d63331'
down_revision: Union[str, None] = '744b833bf40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_directory', sa.Boolean(), nullable=False),
    sa.Column('mapped', sa.Boolean(), nullable=False),
    sa.Column('indexed', sa.Boolean(), nullable=False),
    sa.Column('father_id', sa.Integer(), sa.ForeignKey('spot_files.id'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_files_father_id'), 'spot_files', ['father_id'], unique=False)
    op.create_index(op.f('ix_spot_files_path'), 'spot_files', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spot_files_path'), table_name='spot_files')
    op.drop_index(op.f('ix_spot_files_father_id'), table_name='spot_files')
    op.drop_table('spot_files')
    # ### end Alembic commands ###
