"""update fila: add last_retry_at

Revision ID: 7d99519d923a
Revises: 30fac622f13c
Create Date: 2026-05-15 14:20:49.364171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d99519d923a'
down_revision: Union[str, None] = '30fac622f13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filas', sa.Column('last_retry_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filas', 'last_retry_at')
    # ### end Alembic commands ###
