"""spot-files-extension

Revision ID: 4579992220e6
Revises: f05745d63331
Create Date: 2026-04-01 16:46:39.498966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4579992220e6'
down_revision: Union[str, None] = 'f05745d63331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spot_files', sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('spot_files', sa.Column('size', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_spot_files_extension'), 'spot_files', ['extension'], unique=False)
    op.create_foreign_key(None, 'spot_files', 'spot_files', ['father_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spot_files', type_='foreignkey')
    op.drop_index(op.f('ix_spot_files_extension'), table_name='spot_files')
    op.drop_column('spot_files', 'size')
    op.drop_column('spot_files', 'extension')
    # ### end Alembic commands ###
