"""create_bucket_group_id

Revision ID: 0871ba9ac570
Revises: 64c4c8f988d6
Create Date: 2026-01-05 16:08:26.444200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0871ba9ac570'
down_revision: Union[str, None] = '64c4c8f988d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('group_public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_public_id', name='uq_bucket_groups_group_public_id')
    )
    op.add_column('bucket_files', sa.Column('file_public_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False))
    op.add_column('bucket_files', sa.Column('group_index', sa.Integer(), nullable=False))
    op.add_column('bucket_files', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bucket_files', 'bucket_groups', ['group_id'], ['id'])
    op.drop_column('bucket_files', 'file_id')
    op.add_column('reports', sa.Column('group_public_id', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    op.drop_column('reports', 'arquivo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('arquivo_path', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('reports', 'group_public_id')
    op.add_column('bucket_files', sa.Column('file_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bucket_files', type_='foreignkey')
    op.drop_column('bucket_files', 'group_id')
    op.drop_column('bucket_files', 'group_index')
    op.drop_column('bucket_files', 'file_public_id')
    op.drop_table('bucket_groups')
    # ### end Alembic commands ###
